services:
  - type: web
    name: darkweb-frontend
    buildCommand: cd frontend && yarn install
    startCommand: cd frontend && yarn start
    rootDir: ./
  
  - type: web
    name: darkweb-backend
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python server.py
    rootDir: ./
